#!/usr/bin/env python3

# Created by: Joanna Keza
# Date: May 28, 2025
# This program is the "space Aliens" program for RST-03


import ugame
import stage

# Function for the game scene
def game_scene ():
    
    #Image banks for CircuitPython
    image_bank_background = stage.Bank.from_bmp16("space_aliens_background.bmp")
    image_bank_sprites = stage.Bank.from_bmp16("space_aliens.bmp")
    
    # Sets the tile size
    background = stage.Grid(image_bank_background, 10, 8)
    
    # A sprite that will be updated every frame
    ship = stage.Sprite(image_bank_sprites, 5, 75, 66)
    
    game = stage.Stage(ugame.display, 60)
    # Sets the layers
    game.layers = [ship] + [background]
    game.render_block()
    
    while True:
        
        # redraw sprites
        game.render_sprites([ship])
        game.tick()
    
if __name__ == "__main__":
    game_scene()

